### ISSUE TITLE
How to use with nvim-autopairs ?

### ISSUE THREAD

**Issue by uga-rosa** [hrsh7th/nvim-cmp#14]
This mapping stopped working on c2f872920e0a54cd423212d1693967cbf74cb29a.
```lua
local npairs = require('nvim-autopairs')
npairs.setup {}
_G.cmp_npairs_cr = function ()
  if vim.fn.pumvisible() == 1 then
    return cmp.utils.keymap.expr('<cr>')
  else
    return npairs.autopairs_cr()
  end
end

vim.api.nvim_set_keymap("i", "<cr>", "v:lua.cmp_npairs_cr()", {expr = true, noremap = true})
```

**Comment by hrsh7th** [comment]
I think you don't need any glue setting.

```
local npairs = require('nvim-autopairs')
npairs.setup {}
_G.cmp_npairs_cr = function ()
  return npairs.autopairs_cr()
end

vim.api.nvim_set_keymap("i", "<cr>", "v:lua.cmp_npairs_cr()", {expr = true, noremap = true})
```

The above configuration should be worked.

**Comment by hrsh7th** [comment]
@uga-rosa 
And please set up mapping option with `require'cmp'.setup { ... }`. It specified in README.md

**Comment by uga-rosa** [comment]
Don't work...
![cmp](https://user-images.githubusercontent.com/82267684/129065851-64b8b53c-8201-4e57-8800-e29577ddcc7f.gif)

**Comment by hrsh7th** [comment]
My minimal vimrc works as expected.

```
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !isdirectory(s:plug_dir)
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'windwp/nvim-autopairs'
Plug 'hrsh7th/vim-vsnip'
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
call plug#end()
PlugInstall | quit


lua <<EOF
local cmp = require'cmp'
cmp.setup {
  -- You should change this example to your chosen snippet engine.
  snippet = {
    expand = function(args)
      -- You must install `vim-vsnip` if you set up as same as the following.
      vim.fn['vsnip#anonymous'](args.body)
    end
  },

  -- You must set mapping.
  mapping = {
    ['<C-p>'] = cmp.mapping.item.prev(),
    ['<C-n>'] = cmp.mapping.item.next(),
    ['<C-d>'] = cmp.mapping.scroll.up(),
    ['<C-f>'] = cmp.mapping.scroll.down(),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Replace,
      select = true,
    })
  },

  -- You should specify your *installed* sources.
  sources = {
    { name = 'buffer' }
  },
}

require('nvim-autopairs').setup({
  disable_filetype = { "TelescopePrompt" , "vim" },
})

local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')

-- skip it, if you use another global object
_G.MUtils = {}

MUtils.completion_confirm=function()
  return npairs.autopairs_cr()
end


remap('i' , '<CR>','v:lua.MUtils.completion_confirm()', {expr = true , noremap = true})
EOF
```

**Comment by uga-rosa** [comment]
Hmmm. I can't find any strange settings, but it doesn't work.
I tried many things, but the only thing I could think of as the cause was packer.nvim. It doesn't seem to be a problem here.

**Comment by hrsh7th** [comment]
I think it isn't necessary on currently nvim-cmp.

**Comment by windwp** [comment]
i can make a PR to make autocmd and export the last confirm item after confirm function is execute

**Comment by hrsh7th** [comment]
@windwp What do you want? I think it isn't necessary.

**Comment by hrsh7th** [comment]
OK. I've understand.
I think it should be supported in nvim-cmp itself (by user customizing).

```lua
require'cmp'.setup {
  item = {
    custom = function(completion_item)
      if completion_item.kind == cmp.lsp.CompletionItemKind.Method or Function then
        completion_item.insertText = completion_item.insertText + '($0)'
        completion_item.insertTextFormat = cmp.lsp.InsertTextFormat.Snippet
      end
      return completion_item
    end
  }
}
```

But I will add `CmpConfirmDone` autocmd.

**Comment by hrsh7th** [comment]
```lua
require'cmp'.setup {
  event = {
    on_confirm_done = function(entry)
      -- do something
    end
  }
}
```

I've added the API for it.

**Comment by windwp** [comment]
ok thank i will checking it

**Comment by uga-rosa** [comment]
I create minimal rc.
Can you see if you can reproduce it?

init.lua
```lua
local fn = vim.fn
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"

if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end

require'plugins'
vim.cmd([[autocmd BufWritePost plugins.lua source <afile> | PackerCompile]])
```

lua/plugins.lua

```lua
vim.cmd([[packadd packer.nvim]])

require("packer").startup(function()
  use("wbthomason/packer.nvim")
  use({
    "hrsh7th/nvim-cmp",
    requires = {
      "hrsh7th/cmp-buffer",
    },
    config = function()
      local cmp = require("cmp")
      cmp.setup({
        mapping = {
          ["<C-p>"] = cmp.mapping.prev_item(),
          ["<C-n>"] = cmp.mapping.next_item(),
          ["<C-e>"] = cmp.mapping.close(),
          ["<cr>"] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
          }),
        },
        sources = {
          { name = "buffer" },
        },
      })
    end,
  })
  use({
    "windwp/nvim-autopairs",
    config = function()
      local npairs = require("nvim-autopairs")
      npairs.setup({})

      _G.MUtils = _G.MUtils or {}
      MUtils.completion_confirm = function()
        return npairs.autopairs_cr()
      end

      vim.api.nvim_set_keymap("i", "<cr>", "v:lua.MUtils.completion_confirm()", { expr = true, noremap = true })
    end,
  })
end)
```

**Comment by uga-rosa** [comment]
I also wrote this using vim-plug and the problem did not occur. So I think it might be a compatibility issue with packer.nvim, and I want you to check it in other environments.

**Comment by saadparwaiz1** [comment]
just tried this. can reproduce with packer.nvim but not vim-plug

**Comment by windwp** [comment]
hi i create a new setup function for nvim-cmp
just check readme of nvim-autopairs
i don't use packer but it should working

**Comment by hrsh7th** [comment]
Hm... I will try with packer.nvim

**Comment by hrsh7th** [comment]
I tried to use packer.nvim with the following config and it works as expected.

```lua
local install_path = vim.fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"

if vim.fn.empty(vim.fn.glob(install_path)) > 0 then
  vim.fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end

vim.cmd([[autocmd BufWritePost plugins.lua source <afile> | PackerCompile]])vim.cmd([[packadd packer.nvim]])

require("packer").startup(function()
  use("wbthomason/packer.nvim")
  use({
    "hrsh7th/nvim-cmp",
    requires = {
      "hrsh7th/cmp-buffer",
    },
    config = function()
      local cmp = require("cmp")
      cmp.setup({
        mapping = {
          ["<C-p>"] = cmp.mapping.prev_item(),
          ["<C-n>"] = cmp.mapping.next_item(),
          ["<C-e>"] = cmp.mapping.close(),
          ["<cr>"] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
          }),
        },
        sources = {
          { name = "buffer" },
        },
      })
    end,
  })
  use({
    "windwp/nvim-autopairs",
    config = function()
      local npairs = require("nvim-autopairs")
      npairs.setup({})

      _G.MUtils = _G.MUtils or {}
      MUtils.completion_confirm = function()
        return npairs.autopairs_cr()
      end

      vim.api.nvim_set_keymap("i", "<cr>", "v:lua.MUtils.completion_confirm()", { expr = true, noremap = true })
    end,
  })
end)
```

**Comment by uga-rosa** [comment]
Ok, I understood.
First, we will briefly explain the behavior of packer.nvim.
Normally, the description of plugins is written in a separate file called plugins.lua. This is because compiling that file will load the configuration of plugins faster.
```
vim.cmd([[autocmd BufWritePost plugins.lua source <afile> | PackerCompile]])vim.cmd([[packadd packer.nvim]])
```
The fact that your configuration (no separate files) is fine would mean that this compilation is not done correctly.

**Comment by uga-rosa** [comment]
And I'm not sure why, but mapping the <CR> from nvim-autopairs worked.
```diff
-    ["<cr>"] = cmp.mapping.confirm({
-      behavior = cmp.ConfirmBehavior.Replace,
-      select = true,
-    }),

+require("nvim-autopairs").setup({})
+require("nvim-autopairs.completion.cmp").setup({
+  map_cr = true,
+  map_complete = true,
+})

```

**Comment by hrsh7th** [comment]
Hm... I still can't reproduce it with `lua/plugins.lua` pattern.

```lua
-- init.mini.lua
local fn = vim.fn
local install_path = fn.stdpath("data") .. "/site/pack/packer/start/packer.nvim"

if fn.empty(fn.glob(install_path)) > 0 then
  fn.system({ "git", "clone", "https://github.com/wbthomason/packer.nvim", install_path })
end

require'plugins'
vim.cmd([[autocmd BufWritePost plugins.lua source <afile> | PackerCompile]])
```

```lua
-- lua/plugins.lua
vim.cmd([[packadd packer.nvim]])

require("packer").startup(function()
  use("wbthomason/packer.nvim")
  use({
    "hrsh7th/nvim-cmp",
    requires = {
      "hrsh7th/cmp-buffer",
    },
    config = function()
      local cmp = require("cmp")
      cmp.setup({
        mapping = {
          ["<C-p>"] = cmp.mapping.prev_item(),
          ["<C-n>"] = cmp.mapping.next_item(),
          ["<C-e>"] = cmp.mapping.close(),
          ["<cr>"] = cmp.mapping.confirm({
            behavior = cmp.ConfirmBehavior.Replace,
            select = true,
          }),
        },
        sources = {
          { name = "buffer" },
        },
      })
    end,
  })
  use({
    "windwp/nvim-autopairs",
    config = function()
      local npairs = require("nvim-autopairs")
      npairs.setup({})

      _G.MUtils = _G.MUtils or {}
      MUtils.completion_confirm = function()
        return npairs.autopairs_cr()
      end

      vim.api.nvim_set_keymap("i", "<cr>", "v:lua.MUtils.completion_confirm()", { expr = true, noremap = true })
    end,
  })
end)
```

**Comment by hrsh7th** [comment]
Ah. I found the cause. I will fix it.

**Comment by hrsh7th** [comment]
I've fixed it! Thank you.
https://github.com/hrsh7th/nvim-cmp/commit/5cc6c61a7edea47f70b0a694f1b95f4a49565ba0

**Comment by jabuxas** [comment]
I still have this issue using lsp zero, which depends on nvim cmp. 
```
-- ....
local cmp = require('cmp')
local cmp_select = { behavior = cmp.SelectBehavior.Select }
local cmp_mappings = lsp.defaults.cmp_mappings({
    ['<C-p>'] = cmp.mapping.select_prev_item(cmp_select),
    ['<C-n>'] = cmp.mapping.select_next_item(cmp_select),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
    ["<C-Space>"] = cmp.mapping.complete(),
})

-- .....

local cmp_autopairs = require("nvim-autopairs.completion.cmp")
local cmp_status_ok, cmp = pcall(require, "cmp")
if not cmp_status_ok then
    return
end
cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done({}))

lsp.setup()

```

seems to be possible to use based on this guy's setup https://github.com/redxtech/dotfiles/blob/master/.config/nvim/lua/lsp.lua#L70, but i have no clue what is going wrong.

http://0x0.st/o7qA.mp4 video showing error
