### ISSUE TITLE
Latest commit breaks completion if there are duplicates

### ISSUE THREAD

**Issue by ericpubu** [hrsh7th/nvim-cmp#157]
So with the latest [commit](https://github.com/hrsh7th/nvim-cmp/commit/247538449b60fc5cb6846bc4f2c49410acfb460a)  there is a problem if in the completion list is present a repeated element, as it is not being displayed, but I asumme it is still being indexed causing to expand information not corresponding to the selected item.

Here is an example with gopls and using [friendly-snippets](https://github.com/rafamadriz/friendly-snippets/blob/main/snippets/go.json), the `func`  completion is a keyword for the language server and also is as snippet, and as it is not repeted on the list, the next snippets are expanding the previous one:

https://user-images.githubusercontent.com/18682359/132146274-f61812dc-f421-4127-9a57-0cb249dc74f6.mov

This is not happening on the previous commit, here is the correct behavior using the previous commit:

https://user-images.githubusercontent.com/18682359/132146156-c7f8d0c4-3c70-4cdc-8824-10a93056bb33.mov

**Comment by hrsh7th** [comment]
Thank you. I've fixed.

**Comment by xeluxee** [comment]
This issue is still present, I'm using 1cd5774.
Now there are duplicates but not enough entries are shown.

![cmp0](https://user-images.githubusercontent.com/88047141/133500038-e3a6d094-3614-493c-a5fc-7ea2efcb8fad.png)

A for snippet from `luasnip` source (Snippet) is missing in above screenshot, while `forr` and `foreach` are shown even if they are provided by the same source (`luasnip`).

**Comment by hrsh7th** [comment]
I can't reproduce. What is the `missing` candidate?

**Comment by xeluxee** [comment]
A `for` is missing from popupmenu, a `for` that should be provided by LuaSnip source that is active (as you can see from `forr` and `foreach` snippets).
Only two `for` are shown, the one provided by LuaSnip is missing.

To reproduce:
1. install friendly-snippets, nvim-cmp and LSP and LuaSnip sources.
2. Create a cpp file
3. type `for`
4. You should see something similar to the screenshot above
5. A `for` entry is missing

**Comment by hrsh7th** [comment]
@xeluxee I've tested it with `luasnip` and `vsnip` both (I'm tired)
The `cmp_luasnip` does not show `for` snippet but `cmp-vsnip` shows it.

**Comment by xeluxee** [comment]
Ok @hrsh7th, so you think this issue is related to `cmp_luasnip` and not to `nvim-cmp`?
I think this could be linked to nvim-cmp some way because when I disable LSP source `for` snippet from LuaSnip source becomes visible...
There is a kind of conflict between sources

**Comment by hrsh7th** [comment]
It's definitely source related.

https://user-images.githubusercontent.com/629908/133646481-61918965-488f-4304-bc0b-f51a90a6f08a.mp4
