### ISSUE TITLE
Commit characters break playing back recorded macros

### ISSUE THREAD

**Issue by jasonccox** [hrsh7th/nvim-cmp#186]
I noticed today that nvim-cmp was causing issues with playing back recorded macros, and it looks like the commit characters are to blame.

## Steps to reproduce

1. Set up tsserver language server with the built-in LSP.
2. Set up nvim-cmp with the nvim_lsp source.
3. Open a JavaScript file in a JavaScript project such that LSP completion will work.
4. Record a macro that includes `.` and `(`, for example with `qaoconsole.log('hi')<esc>q`.
5. Playback the macro with `@a` and observe that it writes `console.log('hi')` on a new line as expected.
6. Select an LSP completion, for example manually type `console.l` and then use the completion menu to select the `log` LSP completion.
7. Try again to playback the macro with `@a` and observe that it writes `consolelog'hi')`.

Then add `confirmation = { get_commit_characters = function(_) return {} end }` to your nvim-cmp config (always return no commit characters) and try the above steps again. This time the macro will playback successfully even after selecting an LSP completion.

## My config

```lua
local cmp = require('cmp')

cmp.setup {
  completion = {
    autocomplete = false,
  },

  formatting = {
    -- show completion source in menu
    format = function(entry, vim_item)
      vim_item.menu = ({
        buffer = "[buf]",
        nvim_lsp = "[LSP]",
        nvim_lua = "[Lua]",
        path = "[path]",
      })[entry.source.name]

      return vim_item
    end,
  },

  mapping = {
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-n>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.abort(),
    ['<C-y>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
  },

  snippet = {
    expand = function(args)
      vim.fn['vsnip#anonymous'](args.body) -- requires vim-vsnip
    end,
  },

  sources = {
    -- in priority order
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' },
    { name = 'path' },
    { name = 'buffer' },
  },
}
```

**Comment by hrsh7th** [comment]
I can understand your problem, but it's too difficult ...

Do you know of other complete engines that support this behavior?

**Comment by hrsh7th** [comment]
Ah. I've understand. You don't use auto-completion in `macro recording` time.
If so, I can fix it.

**Comment by hrsh7th** [comment]
Fixed in https://github.com/hrsh7th/nvim-cmp/commit/8fb4ee10759440fd1e1298e4e8b83dff2d9a62a3

**Comment by jasonccox** [comment]
Wow, that was a speedy turnaround -- thanks for looking into this so quickly! Unfortunately, the fix actually made things worse.  Here's a screencast that shows the issue:

https://user-images.githubusercontent.com/43078205/132765967-27b4418a-05a3-45ea-8d72-39f7e4e45d08.mov

**Comment by hrsh7th** [comment]
I think macro is tooooo difficult to support.

I will disable all of features when the macro is recording.

**Comment by jasonccox** [comment]
I don't think disabling features when the macro is recording will fix the issue. The macro records just fine. It's just trying to play back the macro that fails, and I suspect it's related to the mappings that get created for commit characters.

I totally understand that there may not be a good way to fix this and keep supporting commit characters. If that's the case, it would be nice to at least put a note in the readme linking to this issue and mentioning the workaround of setting `confirmation.get_commit_characters` to `function(_) return {} end`.

Either way, thanks for looking into this and for your work on the plugin!

**Comment by JoseConseco** [comment]
I know that Autopairs plugins has similar issue - macro records ok, but on second run  the auto inserted brackets fail. And it that case disabling autopairs, for time of recording macro actually works.   I have to manually close bracktes, but at least I can run the macro multiple times.

**Comment by gikari** [comment]
> Fixed in [8fb4ee1](https://github.com/hrsh7th/nvim-cmp/commit/8fb4ee10759440fd1e1298e4e8b83dff2d9a62a3)

This commit completely broked all my macro replays and normal commands with dots and brackets.

**Comment by hrsh7th** [comment]
@jasonccox I think this issue was fixed now. Could you test with latest?

**Comment by hrsh7th** [comment]
https://user-images.githubusercontent.com/629908/133055790-99ec1209-7b5b-4188-9cbd-8f9e12a63876.mp4

**Comment by jasonccox** [comment]
Unfortunately I'm still seeing the same behavior as I showed in the screencast above. It looks like you're using `MacroS`, `MacroE`, and `MacroRun` commands to record and run your macros, though -- do those do something special that `q<reg>`, `q`, and `@<reg>` don't do?

**Comment by hrsh7th** [comment]
No. It's just a proxy command (I've mapped the `q` to close the buffer.

**Comment by hrsh7th** [comment]
I've re-fixed the macro.

@jasonccox Thank you for your polite and detailed issue report.

**Comment by hrsh7th** [comment]
I think we can't fix it perfectly. The current implementation is enough to use, I think. Sorry...

If I found the improvement point, I will fix it.

**Comment by jasonccox** [comment]
I'm still seeing the same behavior. If you don't think it can be fixed, then I'd recommend reverting to the original behavior (which turned `console.log('hi')` into `consolelog'hi')`); the new behavior (shown in my screencast) is worse, in my opinion.

**Comment by hrsh7th** [comment]
I'm re-fix it... Hm... it's too difficult 🤣

**Comment by jasonccox** [comment]
It does seem to be working as expected after a212356641917e08d4e2ec70201c5e30d8a8339a -- nicely done!
