### ISSUE TITLE
Terminal title flickers when completion menu opens

### ISSUE THREAD

**Issue by adrian5** [hrsh7th/nvim-cmp#309]
#### How to reproduce

Enable vim `title` property, e.g.:

```lua
vim.opt.title = true
vim.opt.titlestring = "%F %r"
```

Then use nvim-cmp and watch title flicker (update to empty, then back to `titlestring` presumably) each time the popup menu opens.

---

The only fix is not to set the `title` option, `lazyredraw` alas does not have the desired effect.

This did not happen until recently and might be related to #289. It's sufficiently annoying, not "personal preference" territory.

**Comment by David-Else** [comment]
In Gnome terminal and Neovim `0.6 master` the title changes from the actual name of the file to `[no name] - NVIM` and back again as you select things.

**Comment by hrsh7th** [comment]
My next task is this. But it is a bit difficult. I didn't know the reason yet.

**Comment by khaveesh** [comment]
In lsp's hover feature, the title flickers for maybe a millisecond and returns back to the original title. But in cmp's case, the filename remains as `[No Name]` until I type something or select any completion item.

**Comment by stormc** [comment]
@Shougo If you don't see the flicker with the code snippet above, then it "solves" it :) So, it does not reproduce the flicker but instead shows how to avoid it, sorry for the inaccuracy.

**Comment by Shougo** [comment]
Oh, so please test the latest nvim-cmp.
If it is not occurred, the issue should be closed.

**Comment by adrian5** [comment]
@Shougo Still happens for me on latest commit `49acc84`:
![nvim-title-flicker](https://user-images.githubusercontent.com/5426924/136969131-ab1b0cec-35df-4e18-92ac-35d165440dda.gif)

**Comment by Shougo** [comment]
OK.  The problem is reproduced when `let &titlestring="%F %r"`.

**Comment by Shougo** [comment]
`nvim_win_set_option()` causes the problem.

**Comment by stormc** [comment]
I agree. My filename-caching `titlestring` function above is a hack/workaround to this problem. And it's too broad in using the cached filename unconditionally for all floating windows (condition: `vim.api.nvim_win_get_config(0).relative ~= ""`). This problem also extends to other than filename information you may put in `titlestring` that is different in the buffer and the floating window.

What would be needed for a real solution is a flag or something to tell nvim not to render `titlestring` for a particular window/popup, maybe set by a `nvim_win_set_option()` option. But that's a nvim-core change...

**Comment by adrian5** [comment]
@stormc Sorry, I missed your earlier post in this thread when I wrote my response to Shougo, my musings might seem a bit redundant in that context.

**Comment by hrsh7th** [comment]
I think this issue was fixed by latest nvim.

**Comment by charbelnicolas** [comment]
Yes, sadly, this issue still persists...

https://user-images.githubusercontent.com/14960414/179118728-4f4822a0-66ac-4a67-93b1-63521d011ec4.mp4

**Comment by Shougo** [comment]
I have tested the behavior, but I cannot reproduce the flicker.
You need to upload the minimal init.vim.

**Comment by Shougo** [comment]
OK.  I have reproduced.  When the documentation is empty, it will be `[No name]`.
I don't know why though.

**Comment by Shougo** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/309#issuecomment-941035010

When no documentation source candidates, the flicker does not exist.
So the original problem is improved.

**Comment by charbelnicolas** [comment]
Yeah, when adding and attaching an LSP it flickers, otherwise it works correctly:

https://user-images.githubusercontent.com/14960414/179129083-05f21646-1724-4683-8330-7a02f2f00575.mp4

**Comment by charbelnicolas** [comment]
> [#309 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/309#issuecomment-941035010)
> 
> When no documentation source candidates, the flicker does not exist. So the original problem is improved.
> 
> [#309 (comment)](https://github.com/hrsh7th/nvim-cmp/issues/309#issuecomment-1041458350)
> 
> The fixed is true. It is another problem.

Hey @Shougo, do you know if there is a way to disable the documentation pop up?

**Comment by Shougo** [comment]
It is documented.

```
How to disable the documentation window?~

  Simply use the following config:
>
  cmp.setup.filetype({ 'markdown', 'help' }, {
    window = {
      documentation = cmp.config.disable
    }
  })
<
```
