### ISSUE TITLE
Undo history was broken

### ISSUE THREAD

**Issue by onosendi** [hrsh7th/nvim-cmp#328]
Code remanents are left over after 'undo'.

NVIM v0.5.0
Build type: Release
LuaJIT 2.1.0-beta3

```lua
local cmp = require'cmp'

cmp.setup({
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },
  mapping = {
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({ select = true }),
  },
  sources = {
    { name = 'nvim_lsp' },
    { name = 'vsnip' },
    { name = 'buffer' },
  }
})
```

**Comment by Shougo** [comment]
Hm.  It seems inteded behavior, because you have leaved insert mode after several editing.
The undo point is splitted.

**Comment by onosendi** [comment]
When I don't `require` nvim-cmp, there are no issues. So it seems to be directly related to the plugin.

**Comment by Shougo** [comment]
I have tested without plugins.
The undo point is splitted after InsertLeave.

**Comment by onosendi** [comment]
I did everything I could to try to narrow down the issue, thinking maybe it was just my config that was causing it. I started with a blank Neovim install, and only installed the plugins necessary to run nvim-cmp. I did this on both MacOS and Arch Linux, and unfortunately the issue still exists.

I did have the same issue with nvim-compe as well. I don't know, maybe that can help you narrow it down on your side. I do find it strange that I'm the only one that has filed an issue with this, which makes me think it is directly related to something I'm doing.

**Comment by onosendi** [comment]
@hrsh7th I don't use lexima.vim. Remember though, I only installed nvim-cmp related plugins and still had the issue.

**Comment by hrsh7th** [comment]
I think this issue relates to this https://github.com/hrsh7th/nvim-cmp/issues/333

**Comment by jason0x43** [comment]
(I'm using 49acc848531b8cbe051c598dddd0cc46ec64f4b4)

**Comment by jason0x43** [comment]
It definitely seems to be related to logic around the popup. As long as the popup never appears, undo works properly (at least in my testing). If the popup appears either automatically or manually (I setup a mapping like https://github.com/hrsh7th/nvim-cmp/issues/178#issuecomment-915231777 to only trigger completion when I hit tab), undo history may break.

**Comment by Shougo** [comment]
Please test Vim's built-in completion `<C-x><C-n>` breaks undo history.
I think it is hard to fix.

**Comment by onosendi** [comment]
@Shougo I turned off nvim-cmp's autocomplete, and used nvim's built-in completion with no issues. I'm not a vim/nvim plugin dev, so I'm not really sure how everything works, but I used coc.vim's autocompletion for a long time with no issues.

**Comment by Shougo** [comment]
I want to test it.  Please upload the minimal config with the reproduce instructions.

**Comment by onosendi** [comment]
Download zip file, unzip, `nvim -u /path/to/minimal-nvim-config/init.lua /path/to/minimal-nvim-config/RandomColorSquare.jsx`, then type out the code like I did in the first video I posted in this thread.
[minimal-nvim-config.zip](https://github.com/hrsh7th/nvim-cmp/files/7334198/minimal-nvim-config.zip)

**Comment by Shougo** [comment]
Hm. I have tested.  The undo something wrong.  I cannot undo whole changes...

**Comment by frangio** [comment]
This happens to me with the custom floating menu, and does not happen with the native menu (`experimental.native_menu = true`).

**Comment by mabugaj** [comment]
> This happens to me with the custom floating menu, and does not happen with the native menu (`experimental.native_menu = true`).

I can confirm that going back to `native_menu` solves the problem. The problem also doesn't occurs with empty buffer just like @onosendi wrote.

**Comment by hrsh7th** [comment]
Related https://github.com/neovim/neovim/issues/11439

**Comment by jacksonludwig** [comment]
> This happens to me with the custom floating menu, and does not happen with the native menu (`experimental.native_menu = true`).

strange, I still get the issue with `experimental.native_menu` enabled

**Comment by flaphoschi** [comment]
> > This happens to me with the custom floating menu, and does not happen with the native menu (`experimental.native_menu = true`).
> 
> strange, I still get the issue with `experimental.native_menu` enabled, but never with manual completion regardless

Correct. The issue persists with `native_menu` but seems to be triggered in less conditions?

**Comment by hrsh7th** [comment]
This is upstream issue.
https://github.com/hrsh7th/nvim-cmp/issues/328#issuecomment-971520557

**Comment by flaphoschi** [comment]
Thank you!
Is it feasible that the underlying issue within neovim depends on how the floating window is implemented or used?

Intel SandyBridge (ThinkPad X220)
- Reproducible on TTY and Wayland with `vim-cmp` and `vim-compe`

AMD Ryzen 4000 (ThinkPad T14 Gen1)
- Reproducible on TTY but nearly impossible to reproduce on Wayland with `vim-cmp`

Using the `native_menu = true` with `vim-compe` helps a little but scrolling through completions triggers the bug anyway. What maybe helps a little is likely causing a separate change in the undo tree e.g. moving cursor, leaving insert mode or so.

**Comment by flaphoschi** [comment]
*Question*

I think I've noticed something which could help. The bug is triggered only when the a second "floating auto-completion window" is also showing the return type. The return types are here not shown always - I don't know why. Is there a way to instruct nvim-cmp or LSP to show the return types in a different way?

**Comment by flaphoschi** [comment]
:facepalm: 
When the terminal is small the `return type` isn't show and the bug isn't triggered. I some time to figure out this difference :roll_eyes: 
The question remains - what is special about the `return types`?

**Comment by flaphoschi** [comment]
:facepalm: 
With **nvim-compe** the `return type` isn't show on small terminals and the bug isn't triggered. I required me some time to figure out this difference :roll_eyes: 

**nvim-cmp** always shows the `return type` and therefore always triggers the bug, whatever size the terminal has. Is this a hint and can the return types shown in a different way? Maybe within same window as the function names and parameters?

**Comment by hrsh7th** [comment]
@flaphoschi What is the `return type`? Could you provide the screencast?

**Comment by flaphoschi** [comment]
I will provide two screencasts later today :slightly_smiling_face:

**Comment by flaphoschi** [comment]
In both screen-casts you will see `nvim-compe` and not `nvim-cmp` because only `nvim-cmp` hides the return type, if the terminal is to small:

https://user-images.githubusercontent.com/3392113/148943976-3d517289-9392-4bad-81cb-58c30d0c3802.mp4
Bug triggered, wide terminal which shows also the return type of a selected member function, after 'undo' the erroneous line is remaining in the buffer. 


https://user-images.githubusercontent.com/3392113/148944141-f50f962f-8f43-4da4-be6d-94a1f3aefe00.mp4
Bug not triggered, less wide terminal, the auto-completion doesn't show the return type - likely to save some screen space - and the `undo` is successfully.


My comment on the [upstream bug 11439 ](https://github.com/neovim/neovim/issues/11439#issuecomment-1008443020) also shows `vim-cmp`, which always shows the return type. My assumption is that only the "window" which is showing the return type is causing the bug. Of course we want return types show but hopefully this gives a hint how to avoid the issue?

**Comment by flaphoschi** [comment]
I don't have the impression nvim is working on the issue though it is critical. May I suggest therefore a viable workaround? The plugin [vim-lsp](https://github.com/natebosch/vim-lsc) shows the all possible functions and return types together:
![nvim_lscp](https://user-images.githubusercontent.com/3392113/149944817-c1fa4c41-e968-4724-b67f-361115afbc87.png)

I don't know if the implementation is using one window (nvim) or popup (vim) but it looks like one. I've tested it with vim and nvim and the buffer isn't corrupted by undo operations. On the other hand nvim-cmp shows only the return type of the currently selected function (completion), likely intentional. I will require a change in implementation. Pros and Cons:

```
+ issue mitigated
+ complete overview what is returned by functions
- more clutter on screen
- upstream issue not fixed
```

I know it is undesirable to change the implementation you have chosen as author because of an external problem. Thanks for you work :slightly_smiling_face:

**Comment by jdrouhard** [comment]
@flaphoschi It’s not just showing the return type that breaks it. It’s some other core underlying side effects of using a floating window instead of the built in completion menu.

For me, it’s easily reproducible with a completion menu with no “return types” at all, but the problem disappears when I disable the new style floating window.

**Comment by flaphoschi** [comment]
We are all using different LSP-Servers which makes it somehow difficult. I aware that the "return types" itself are not the the issue but what happens when they are shown (some drawing function or another unknown side-effect). Turning the new floating window `off` and using native menu is maybe a fix for some LSP-Servers - sadly not for Clangd.

**Comment by jason0x43** [comment]
From the screencast it looks like the return type may be rendered in a floating window (it disappears shortly after the main completion popup), which might explain why return types are causing problems even when the native completion menu is being used.

**Comment by jdrouhard** [comment]
@flaphoschi I'm also using clangd and I get the issue even when the return type is not displayed. I don't think it's directly related. It's related to using a floating window in general.

**Comment by flaphoschi** [comment]
I didn't knew how to suppress the display of the return type but figured out that `docs_view.lua` is responsible. Because I'm clueless about Lua I just added [here](https://github.com/hrsh7th/nvim-cmp/blob/8fc8d31cf451b8becb39087aa2190bee29a8b009/lua/cmp/view/docs_view.lua#L29):

```
  if documentation then
    return
  end
```

And the docs with the return types doesn't appear anymore. And as you said the bug is also triggered without it :disappointed: 
Probably another difference between `nvim-cmp` and `nvim-comp`?

**Comment by lyokha** [comment]
Hi. Test my neovim patch in the neovim's upstream issue. It looks like it fixes the bug.

**Comment by lyokha** [comment]
Just rebuilt nvim with the patch from https://github.com/neovim/neovim/pull/17150. It works, no undo lost detected!

**Comment by hrsh7th** [comment]
The PR has merged. I'll close this after neovim v0.7 is released.

**Comment by onosendi** [comment]
@hrsh7th Sweet! Thank you, and everyone else in this thread for your work.

**Comment by vdeurzen** [comment]
I seem to have a similar issue as described here, but I'm not sure it's exactly the same. I'm running nvim @ HEAD (including the patch https://github.com/neovim/neovim/pull/17150) and have updated nvim-cmp today. This doesn't happen every time (often only after I've already accepted a few completions), but when I complete a function call (accepting it with `<C-y>`, default mapping) suggested by LSP (gopls at the moment) the buffer is reset to some point in history. Some times only a recent edit, some times all the way back to an empty file.

I'm not sure how to debug this. I've reduced the configuration for nvim-cmp to only the suggested configuration and the problem seems to persist. What could I do to debug this? Since this issue is so close to mine I haven't tried running with a minimal config yet, but I can if that helps.

**Comment by hrsh7th** [comment]
@vdeurzen Please screencast for explaining the issue. I think the minimal reproduction configuration is not useful for this problem...

**Comment by hrsh7th** [comment]
I can't imagine that nvim-cmp undo all modification when press `<C-y>`.
I think your configuration is broken. Could you upload your configuration?

**Comment by vdeurzen** [comment]
Just the nvim-cmp part or everything? This is what I have for nvim-cmp:
```
local lspkind = require("lspkind")
lspkind.init()


local cmp_autopairs = require("nvim-autopairs.completion.cmp")

local cmp = require("cmp")
cmp.setup({
	snippet = {
		expand = function(args)
			require("luasnip").lsp_expand(args.body)
		end,
	},

	mapping = {
		["<C-d>"] = cmp.mapping(cmp.mapping.scroll_docs(-4), { "i", "c" }),
		["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(4), { "i", "c" }),
		["<C-e>"] = cmp.mapping({
			i = cmp.mapping.abort(),
			c = cmp.mapping.close(),
		}),
	},

	sources = cmp.config.sources({
		{ name = "nvim_lsp" },
		{ name = "nvim_lua" },
		{ name = "path" },
		{ name = "luasnip" },
		{ name = "buffer", keyword_length = 5 },
	}),

	formatting = {
		format = lspkind.cmp_format({
			with_text = true,
			menu = {
				buffer = "[buf]",
				nvim_lsp = "[LSP]",
				nvim_lua = "[api]",
				path = "[path]",
				luasnip = "[snip]",
			},
		}),
	},

	experimental = {
		native_menu = true,
		ghost_text = false,
	},
})

cmp.event:on("confirm_done", cmp_autopairs.on_confirm_done({ map_char = { tex = "" } }))
```
I also use `vim-which-key` which also deals with keybindings, but this issue started recently after I pulled neovim changes about 3 - 4 days ago. Before then nothing was wrong and everything worked quite well.

**Comment by hrsh7th** [comment]
@vdeurzen Could you try this configuration? (I'd removed some of the plugin-related things.

```
local cmp = require("cmp")
cmp.setup({
	snippet = {
		expand = function(args)
			require("luasnip").lsp_expand(args.body)
		end,
	},

	mapping = {
		["<C-d>"] = cmp.mapping(cmp.mapping.scroll_docs(-4), { "i", "c" }),
		["<C-f>"] = cmp.mapping(cmp.mapping.scroll_docs(4), { "i", "c" }),
		["<C-e>"] = cmp.mapping({
			i = cmp.mapping.abort(),
			c = cmp.mapping.close(),
		}),
	},

	sources = cmp.config.sources({
		{ name = "nvim_lsp" },
	}),

	experimental = {
		native_menu = true,
	},
})
```

**Comment by vdeurzen** [comment]
@hrsh7th Unfortunately it still keeps happening. I noticed that I can press `enter` which will select the entry but not close the menu. Could this be something to do with the menu and its closing?

**Comment by hrsh7th** [comment]
Don't you get any error message? e.g. :messages

**Comment by vdeurzen** [comment]
Unfortunately no, the only message you see is `"main.go" [Modified] 5 lines --40%--` which you should be able to see in the screen cast.

**Comment by vdeurzen** [comment]
Is there a way to trace what happens when I press this key combination?

**Comment by vdeurzen** [comment]
After a lot of printf debugging I found that the problem is no longer reproducing after I switched from LuaSnip to Snippy. I also tried checking out an earlier version of LuaSnip, but had some trouble with their repository (not sure if that's a Packer issue or a Git issue or something else :sweat_smile:.

**Comment by hrsh7th** [comment]
This issue is solved by latest neovim.

**Comment by onosendi** [comment]
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@BigSur

Issue still remains.

**Comment by phrydo** [comment]
nvim 0.6.1 was released on the 1st of jan, it doesn't have the fix

**Comment by onosendi** [comment]
Ah, gotcha.
