### ISSUE TITLE
Tab does not work correctly in cmdline-completion

### ISSUE THREAD

**Issue by rignet-bicteg** [hrsh7th/nvim-cmp#875]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

6.1

### Minimal reproducible full config

```
require('packer').startup(function()
  use 'wbthomason/packer.nvim'

  use {
    'hrsh7th/nvim-cmp',
    requires = {
      {'hrsh7th/cmp-nvim-lsp'},
      {'hrsh7th/cmp-buffer'},
      {'L3MON4D3/LuaSnip'},
      {'saadparwaiz1/cmp_luasnip'},
    }
  }
end)

local cmp = require('cmp')
cmp.setup({
  snippet = {
    expand = function(args)
      require('luasnip').lsp_expand(args.body)
    end,
  },
  mapping = {
    ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
    ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
    ['<C-d>'] = cmp.mapping.scroll_docs(-4),
    ['<C-f>'] = cmp.mapping.scroll_docs(4),
    ['<C-Space>'] = cmp.mapping.complete(),
    ['<C-e>'] = cmp.mapping.close(),
    ['<CR>'] = cmp.mapping.confirm({
      behavior = cmp.ConfirmBehavior.Insert,
      select = true,
    }),
  },
  sources = cmp.config.sources(
    {
      { name = 'nvim_lsp' },
      { name = 'luasnip' },
    },
    {
      {
        name = 'buffer',
        option = {
          get_bufnrs = function()
            return vim.api.nvim_list_bufs()
          end
        }
      },
    }
  )
})
```

### Description

Hello,

When I open a file and do `:e <Tab>` I see a `I^` char inserted. No completion.

I'll upload a video to showcase as well.

### Steps to reproduce

```
nvim -u min.lua
:e <Tab>
```

### Expected behavior

See autocompletion of commands and paths

### Actual behavior

`^I` inserted and no autocompletion

**Comment by hrsh7th** [comment]
Please do *NOT* use packer.nvim for reproduction.
I'll translate it to `vim-plug` version and check this.

**Comment by hrsh7th** [comment]
Reproduced. I'll check it.

**Comment by rignet-bicteg** [comment]
Yeah, thanks, here's the reproduction via vimplug

```
call plug#begin()
    Plug 'neovim/nvim-lspconfig'
    Plug 'hrsh7th/cmp-nvim-lsp'
    Plug 'hrsh7th/cmp-buffer'
    Plug 'hrsh7th/nvim-cmp'
    Plug 'L3MON4D3/LuaSnip'
    Plug 'saadparwaiz1/cmp_luasnip'
call plug#end()

set completeopt=menu,menuone,noselect

lua <<EOF
    local cmp = require('cmp')

    cmp.setup({
    snippet = {
        expand = function(args)
        require('luasnip').lsp_expand(args.body)
        end,
    },
    mapping = {
        ['<C-n>'] = cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
        ['<C-p>'] = cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
        ['<C-d>'] = cmp.mapping.scroll_docs(-4),
        ['<C-f>'] = cmp.mapping.scroll_docs(4),
        ['<C-Space>'] = cmp.mapping.complete(),
        ['<C-e>'] = cmp.mapping.close(),
        ['<CR>'] = cmp.mapping.confirm({
        behavior = cmp.ConfirmBehavior.Insert,
        select = true,
        }),
    },
    sources = cmp.config.sources(
        {
        { name = 'nvim_lsp' },
        { name = 'luasnip' },
        },
        {
        {
            name = 'buffer',
            option = {
            get_bufnrs = function()
                return vim.api.nvim_list_bufs()
            end
            }
        },
        }
    )
    })

    local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
EOF
```

**Comment by axieax** [comment]
Hi @hrsh7th, not sure why this doesn't fix it for me. The specific commit which broke my config and caused similar behaviour is 801a9f98bbae14135be3a04515b9350b145ce25b. My cmp setup config can be found [here](https://github.com/axieax/dotconfig/blob/main/nvim/lua/axie/lsp/completion.lua).

**Comment by gleachkr** [comment]
I'm affected by this as well. I think it has something to do with attaching a cmp.mapping to `<Tab>`. Removing this mapping in my configuration hides the problem. I notice that @axieax's example config also seems to map `<Tab>`.

**Comment by wookayin** [comment]
3192a0c broke keymapping...  https://github.com/hrsh7th/nvim-cmp/issues/888

**Comment by vanarok** [comment]
This bug still exists even with the latest changes.

**Comment by kovasap** [comment]
This bug still seems to exist for me too, can this issue be reopened?

**Comment by doums** [comment]
I confirm, I still have this bug too. I use the following setup:
```
cmp.setup({
  mapping = {
    ['<tab>'] = tab_key,
    ['<S-tab>'] = stab_key,
    ['<Down>'] = cmp.mapping(
      cmp.mapping.select_next_item({ behavior = cmp.SelectBehavior.Select }),
      { 'i' }
    ),
    ['<Up>'] = cmp.mapping(
      cmp.mapping.select_prev_item({ behavior = cmp.SelectBehavior.Select }),
      { 'i' }
    ),
    ['<M-p>'] = cmp.mapping(cmp.mapping.scroll_docs(-4), { 'i', 'c' }),
    ['<M-o>'] = cmp.mapping(cmp.mapping.scroll_docs(4), { 'i', 'c' }),
    ['<C-space>'] = cmp.mapping(cmp.mapping.complete(), { 'i', 'c' }),
    ['<C-e>'] = cmp.mapping({
      i = cmp.mapping.abort(),
      c = cmp.mapping.close(),
    }),
    ['<cr>'] = cmp.mapping.confirm({ select = true }),
  },
  snippet = {
    expand = function(args)
      ls.lsp_expand(args.body)
    end,
  },
  completion = { completeopt = 'menu,menuone,noinsert' },
  sources = {
    { name = 'luasnip' },
    { name = 'nvim_lsp' },
    { name = 'nvim_lua' },
    { name = 'path' },
    { name = 'buffer' },
  },
  window = {
    completion = { border = nil },
    documentation = { border = { '', '', '', ' ', '', '', '', ' ' } },
  },
  formatting = {
    format = function(entry, vim_item)
      vim_item.menu = ({
        buffer = '⌈buf⌋',
        nvim_lsp = '⌈lsp⌋',
        luasnip = '⌈snip⌋',
        nvim_lua = '⌈lua⌋',
        path = '⌈path⌋',
      })[entry.source.name]
      return vim_item
    end,
  },
})
```

**Comment by topaxi** [comment]
Ended up here as well as cmdline command mode completion doesn't seem to work for me.

**Comment by camoz** [comment]
I'm experiencing this, too. Btw I'm not using cmp's `:` completion (i.e. no `cmp.setup.cmdline(':', {...})`), but the native one.

For me, the issue only shows up after a while. When starting a new neovim instance, it always works as expected, but at some point the issue appears. I'm not able to find what exactly triggers it...

Can this issue be re-opened, please?

**Comment by hrsh7th** [comment]
Please creaye new issue with reproduction config.

I can't do anything without new indormation.

I'll ignore this thread if anyone does not provide reproduction *full* config.

**Comment by axieax** [comment]
@camoz I’m still experiencing similar issues in my issue #1454 which @hrsh7th recently closed but is still unresolved. Perhaps it’s relevant to yours?

**Comment by mar-muel** [comment]
Hi all! I don't have any deep understanding of why this bug (?) occurs, so I'm not 100% sure whether the following would not break something else in your setup, but it worked for me!

My initial config (broken):
```lua
local lsp = require('lsp-zero')
local cmp = require('cmp')
local luasnip = require('luasnip')
local keymap = require('cmp.utils.keymap')

lsp.setup_nvim_cmp({
    mapping = {
        -- from: https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#intellij-like-mapping
        ["<Tab>"] = cmp.mapping(
            function(fallback)
                -- This little snippet will confirm with tab, and if no entry is selected, will confirm the first item
                if cmp.visible() then
                    local entry = cmp.get_selected_entry()
                    if not entry then
                        cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
                    else
                        cmp.confirm()
                    end
                elseif luasnip.expand_or_jumpable() then
                    luasnip.expand_or_jump()
                else
                    fallback()
                end
            end, {"i","s","c",}),
        ["<S-Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.jumpable(-1) then
                luasnip.jump(-1)
            else
                fallback()
            end
        end, {"i", "s"}),
        ['<CR>'] = cmp.mapping.confirm(),
        ['<C-n>'] = cmp.mapping.select_next_item(),
        ['<C-p>'] = cmp.mapping.select_prev_item(),
    }
})
```

Fixed version:
```lua
lsp.setup_nvim_cmp({
    mapping = {
        -- from: https://github.com/hrsh7th/nvim-cmp/wiki/Example-mappings#intellij-like-mapping
        ["<Tab>"] = cmp.mapping(
            function(fallback)
                -- This little snippet will confirm with tab, and if no entry is selected, will confirm the first item
                if cmp.visible() then
                    print("cmp visible");
                    local entry = cmp.get_selected_entry()
                    if not entry then
                        cmp.select_next_item({ behavior = cmp.SelectBehavior.Select })
                    else
                        cmp.confirm()
                    end
                elseif luasnip.expand_or_jumpable() then
                    luasnip.expand_or_jump()
                else
                    if vim.fn.pumvisible() == 0 then
                        vim.api.nvim_feedkeys(keymap.t('<C-z>'), 'in', true)
                    else
                        vim.api.nvim_feedkeys(keymap.t('<C-n>'), 'in', true)
                    end
                end
            end, {"i","s","c",}),
        ["<S-Tab>"] = cmp.mapping(function(fallback)
            if cmp.visible() then
                cmp.select_prev_item()
            elseif luasnip.jumpable(-1) then
                luasnip.jump(-1)
            else
                if vim.fn.pumvisible() == 0 then
                    vim.api.nvim_feedkeys(keymap.t('<C-z><C-p><C-p>'), 'in', true)
                else
                    vim.api.nvim_feedkeys(keymap.t('<C-p>'), 'in', true)
                end
            end
        end, {"i", "s"}),
        ['<CR>'] = cmp.mapping.confirm(),
        ['<C-n>'] = cmp.mapping.select_next_item(),
        ['<C-p>'] = cmp.mapping.select_prev_item(),
    }
})
```



It's taken from the fix commit here https://github.com/hrsh7th/nvim-cmp/commit/3192a0c57837c1ec5bf298e4f3ec984c7d2d60c0

**Comment by lutalli** [comment]
I'm still experiencing this issue randomly. When I type commands like `:e` in command mode and then press `<Tab>` attempting to auto complete the file path, sometimes it only produces `^I`.
