### ISSUE TITLE
Invalid color settings passed to nvim_set_hl

### ISSUE THREAD

**Issue by IsaacClank** [hrsh7th/nvim-cmp#961]
### FAQ

- [X] I have checked the [FAQ](https://github.com/hrsh7th/nvim-cmp/blob/15f08a8faa22d52480cdcb9ef9ca698120f04363/doc/cmp.txt#L616) and it didn't resolve my problem.

### Issues

- [X] I have checked [existing issues](https://github.com/hrsh7th/nvim-cmp/issues) and there are no open or closed issues with the same problem.

### Neovim Version

v0.8.0-dev

### Minimal reproducible full config

```lua
local packer_repo = 'https://github.com/wbthomason/packer.nvim'
local packer_installation_path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'

vim.fn.system({ 'git', 'clone', '--depth=1', packer_repo, packer_installation_path })
vim.cmd [[packloadall]]

require('packer').startup(function(use)
	use {
		'wbthomason/packer.nvim',
		{
			'neovim/nvim-lspconfig',
			requires = { 'williamboman/nvim-lsp-installer' }
		},
		{
			'hrsh7th/nvim-cmp',
			requires = {
				{ 'L3MON4D3/LuaSnip' },
				{ 'hrsh7th/cmp-buffer' },
				{ 'hrsh7th/cmp-cmdline' },
				{ 'hrsh7th/cmp-nvim-lsp' },
				{ 'hrsh7th/cmp-path' },
				{ 'hrsh7th/nvim-cmp' },
				{ 'saadparwaiz1/cmp_luasnip' },
			},
		},
		{ 'nvim-treesitter/nvim-treesitter' },
	}

	require('packer').sync()
	require('packer').compile()
end)

vim.api.nvim_create_autocmd('User', {
	pattern = 'PackerCompileDone',
	callback = function()
		local completion = require('cmp')
		local snippet = require('luasnip')

		local function has_words_before()
			local line, col = unpack(vim.api.nvim_win_get_cursor(0))
			return col ~= 0 and vim.api.nvim_buf_get_lines(0, line - 1, line, true)[1]:sub(col, col):match("%s") == nil
		end

		local function on_tab(fallback)
			if completion.visible() then
				completion.select_next_item()
			elseif snippet.expand_or_jumpable() then
				snippet.expand_or_jump()
			elseif has_words_before() then
				completion.complete()
			else
				fallback()
			end
		end

		completion.setup({
			snippet = {
				expand = function(args) snippet.lsp_expand(args.body) end
			},

			mapping = completion.mapping.preset.insert({
				['<C-b>'] = completion.mapping.scroll_docs(-4),
				['<C-f>'] = completion.mapping.scroll_docs(4),
				['<C-Space>'] = completion.mapping.complete(),
				['<C-e>'] = completion.mapping.abort(),
				['<CR>'] = completion.mapping.confirm({ select = true }),

				["<Tab>"] = completion.mapping(on_tab, { "i", "s" }),
				["<S-Tab>"] = completion.mapping(function(fallback)
					if completion.visible() then
						completion.select_prev_item()
					elseif snippet.jumpable(-1) then
						snippet.jump(-1)
					else
						fallback()
					end
				end, { "i", "s" }),
			}),

			sources = completion.config.sources(
			{
				{ name = 'nvim_lsp' },
				{ name = 'luasnip' },
			},
			{ { name = 'buffer' } }
			)
		})

		local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())

		require'lspconfig'.cssls.setup {
			capabilities = capabilities,
		}
	end
})
```

### Description

I'm not very familiar with either Neovim or nvim-cmp but it seems the issue is caused by mismatching data type. I believe there was a recent change in to `highlight.inherit` in #956 

```lua
-- In lua/cmp/utils/highlight.lua

highlight.inherit = function(name, source, settings)
  for _, key in ipairs(highlight.keys) do
    if not settings[key] then
      local v = vim.fn.synIDattr(vim.fn.hlID(source), key)
      if key ~= 'fg' and key ~= 'bg' then
        v = v == 1
      end
      if v then
        settings[key] = v == '' and 'NONE' or v -- <-- v is a string here, when it needs to be a number
      end
    end
  end
  vim.pretty_print(settings)
  vim.api.nvim_set_hl(0, name, settings)
end

return highlight
```

Here's my small workaround:

```lua
-- In lua/cmp/utils/highlight.lua

highlight.inherit = function(name, source, settings)
  for _, key in ipairs(highlight.keys) do
    if not settings[key] then
      local v = vim.fn.synIDattr(vim.fn.hlID(source), key)
      if key ~= 'fg' and key ~= 'bg' then
        v = v == 1
      end
      if v then
        settings[key] = v == '' and 'NONE' or tonumber(v) -- <-- convert to a number
      end
    end
  end
  vim.pretty_print(settings)
  vim.api.nvim_set_hl(0, name, settings)
end

return highlight
```

### Steps to reproduce

- Use the provided init.lua.
- On first load, the plugins are automatically installed.
- On subsequent load, the error is output

### Expected behavior

I expect there is no error.

### Actual behavior

Here is the error output:

```
Vim:E5113: Error while calling lua chunk: ...e/pack/packer/start/nvim-cmp/lua/cmp/utils/highlight.lua:28: '0' is not a valid color

stack traceback:
        [C]: in function 'nvim_set_hl'
        ...e/pack/packer/start/nvim-cmp/lua/cmp/utils/highlight.lua:28: in function 'inherit'
        ...hare/nvim/site/pack/packer/start/nvim-cmp/plugin/cmp.lua:25: in function 'callback'
        ...ite/pack/packer/start/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        ...hare/nvim/site/pack/packer/start/nvim-cmp/plugin/cmp.lua:37: in main chunk
        [C]: in function 'cmd'
        /home/isaac/.config/nvim/init.lua:18: in main chunk
stack traceback:
        [C]: in function 'nvim_command'
        ...cker/start/nvim-treesitter/lua/nvim-treesitter/utils.lua:63: in function 'setup_commands'
        ...ack/packer/start/nvim-treesitter/lua/nvim-treesitter.lua:14: in function 'setup'
        .../packer/start/nvim-treesitter/plugin/nvim-treesitter.lua:9: in main chunk
        [C]: in function 'cmd'
        /home/isaac/.config/nvim/init.lua:18: in main chunk
stack traceback:
        [C]: in function 'cmd'
        /home/isaac/.config/nvim/init.lua:18: in main chunk
```

A quick call to `vim.pretty_print` outputs the apparently "invalid" color value:

```
{
  bg = "NONE",
  default = true,
  fg = "0"
}
```

**Comment by ZuseZ4** [comment]
Same for neovim 0.7.0

**Comment by hrsh7th** [comment]
Coyld someone create PR? Sorry. I'm now out of home.

I'm afraid to workaround solution.
I think the `fg` can be color-name or hex...

**Comment by npmaile** [comment]
The above patch is the best me and a couple of discord friends could come up with

**Comment by hrsh7th** [comment]
Fixed. Thank you for all!

**Comment by prg318** [comment]
This appears to still be an issue as of 9a0c639ac2324e6e9ecc54dc22b1d32bb6c42ab9:

```
Error detected while processing /home/user/.vim/plugged/nvim-cmp/plugin/cmp.lua:
E5113: Error while calling lua chunk: .../user/.vim/plugged/nvim-cmp/lua/cmp/utils/highlight.lua:28: 'fg' is not a valid color
stack traceback:
        [C]: in function 'nvim_set_hl'
        .../user/.vim/plugged/nvim-cmp/lua/cmp/utils/highlight.lua:28: in function 'inherit'
        /home/user/.vim/plugged/nvim-cmp/plugin/cmp.lua:29: in function 'callback'
        /home/user/.vim/plugged/nvim-cmp/lua/cmp/utils/autocmd.lua:49: in function 'emit'
        /home/user/.vim/plugged/nvim-cmp/plugin/cmp.lua:37: in main chunk
```

Let me know if I should file another issue for this or if this issue should be used to track this.  Thanks

**Comment by 0xcharly** [comment]
In case this helps others…

I had the same issue persisting despite the fix in this PR.

The problem was indeed with my Colorbuddy theme, in particular because of the value of the `Pmenu` color group.

That Colorbuddy theme was defining a color named `fg` (_eg._ `Color.new('fg', '#000000')`).  `c.fg` is a ["special color"](https://github.com/tjdevries/colorbuddy.nvim/blob/master/lua/colorbuddy/color.lua#L215) for Colorbuddy, which actual value seems to be ignored: I didn't look too much into it, but after quickly glancing at the source, it seems that using `c.fg` in a Colorbuddy theme will [always be substituted with `"fg"`](https://github.com/tjdevries/colorbuddy.nvim/blob/master/lua/colorbuddy/color.lua#L219-L222) in the highlight definition, regardless of the actual value specified in the theme.
Since my theme was defining `c.fg` and using this as foreground color in several group definitions, it meant that those color groups were using `"fg"` as attribute value (_eg._ `Pmenu guifg=fg`) as opposed to the actual color (_eg._`Pmenu guifg=#000000`).

This, in itself, is working as intended, as per the [`nvim_set_hl(…)` documentation](https://neovim.io/doc/user/api.html): "_The fg and bg keys also accept the string values `"fg"` or `"bg"` which act as aliases to the corresponding foreground and background values of the [Normal](https://neovim.io/doc/user/intro.html#Normal) group._".

However, this color was also used in my theme to define the `Normal` group (_ie._ `Group.new('Normal', c.fg, …)`), which meant that the `Normal` group was using the special value `"fg"` as well (`Normal guifg=fg`), essentially referencing itself.

As per the [`nvim_set_hl(…)` documentation](https://neovim.io/doc/user/api.html): "_If the Normal group has not been defined, using these values results in an error._", which I believe was the underlying issue (in that `Normal` was referencing itself, and thus not being defined?).  It's surprising that this has not been a problem so far…

---

A straightforward fix is to rename the theme-defined "fg" color to something else, _eg._ replace:

```lua
Color.new('fg', …)
```

with

```lua
Color.new('fgOnCanvas', …)
```

(and updating all references to it, from `c.fg` to `c.fgOnCanvas`).

---

Another fix is to keep the existing definition, but **also** define the new color `Color.new('fgOnCanvas', …)`, and **only** replace the definition of the `Normal` group, _eg._ replace:

```lua
Group.new('Normal', c.fg, …)
```

with

```lua
Color.new('fgOnCanvas', …)
Group.new('Normal', c.fgOnCanvas, …)
```

This way, the `Normal` group definition is fixed in that it uses a proper color (`Normal guifg=#000000`) and the other groups are still using the special value `"fg"` to reference the `Normal` group (`Pmenu guifg=fg`).

The benefits of this approach is that it still leverages the `"fg"` special value to link to the `Normal` group definition, and reduces the number of changes to make to the theme.  However, it can also be confusing because `c.fg` is defined, but its actual value is ignored.

In this case, I'd recommend using `nil` for `c.fg` to limit the confusion:

```lua
Color.new('fg', nil) -- Special value "fg", which references the "Normal" group.  Actual color value ignored.
```
